services:

  kafka-broker:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes     # Bitnami-specific flag for easy dev
      - KAFKA_CFG_LOG_RETENTION_HOURS=72 # how long to keep older messages on the wsl distro vhdx
    volumes:
      - kafka-data:/bitnami/kafka

  poller:
    build:
      context: ./poller
    container_name: eonet-poller
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      - POLL_MODE=dev # remember to set this to `prod` to ingest entire `events.json`

  flink-jobmanager:
    image: flink:2.0.0
    container_name: flink-jobmanager
    ports:
      - "8081:8081"  # Flink UI
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - kafka-broker
    volumes:
      - ./flink-sql:/opt/sql
      - ./flink-plugins/flink-sql-connector-kafka-4.0.0-2.0.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar

  flink-taskmanager:
    image: flink:2.0.0
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager # how many expected streaming jobs running
      - | 
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./flink-sql:/opt/sql
      - ./flink-plugins/flink-sql-connector-kafka-4.0.0-2.0.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar

volumes:
  kafka-data:
