networks:
  app-tier:
    driver: bridge

services:

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    networks:
      - app-tier
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes     # Bitnami-specific flag for easy dev
      - KAFKA_CFG_LOG_RETENTION_HOURS=72 # how long to keep older messages on the wsl distro vhdx

  poller:
    build:
      context: ./ingestion
    container_name: eonet-poller
    networks:
      - app-tier
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Used inside poller.py
    restart: on-failure

volumes:
  kafka-data:
