version: '3.8'

services:

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'   # don't let kafka auto-create topics; always create topics explicitly ahead
    command: ["./bin/kafka-server-start.sh", "./config/kraft/server.properties"]

  poller:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    container_name: eonet-poller
    depends_on:
      - kafka
