  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_DATABASE_URI: ""
      MAPBOX_API_KEY: ""
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - postgres
